extend type Query {
    groupMembers(id: UUID, page: Int, size: Int): GroupMemberConnection
}

extend type Mutation {
    removeGroupMember(id: UUID): MessageResponse
    addGroupMember(request: GroupMemberInput): EntityResponseGroupMember
    acceptGroupInvitation(id: UUID): MessageResponse
    rejectGroupInvitation(id: UUID): MessageResponse
}

type GroupMemberConnection implements Connection {
    pageInfo: PageInfo!
    totalCount: Int!
    results: [GroupMemberDTO]
}

type GroupMemberDTO {
    id: UUID
    workoutGroupId: UUID
    user: SimpleUserDTO
    status: String
    createdAt: String
}

input GroupMemberInput {
    groupId: UUID!
    invitedUsername: String!
}

type EntityResponseGroupMember implements EntityResponse {
    message: String
    timestamp: String
    result: GroupMemberDTO
}
